apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: government-api-binding
  namespace: application
  labels:
    app: government-api
subjects:
- kind: ServiceAccount
  name: government-api-sa
  namespace: application
roleRef:
  kind: Role
  name: government-api-role
  apiGroup: rbac.authorization.k8s.io

