apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loan-validator-portal-binding
  namespace: application
  labels:
    app: loan-validator-portal
subjects:
- kind: ServiceAccount
  name: loan-validator-portal-sa
  namespace: application
roleRef:
  kind: Role
  name: loan-validator-portal-role
  apiGroup: rbac.authorization.k8s.io

