apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allow-only-trusted-registries
  annotations:
    policies.kyverno.io/title: Disallow Privileged Containers
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images must come from approved registries. This policy ensures that
      only container images from whitelisted registries.
spec:
  validationFailureAction: enforce
  rules:
    - name: validate-image-registry
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Images must come from approved registries"
        pattern:
          spec:
            containers:
            image: 
              - "daasnigeria/*"
              - "otel/*"
              - "postgres:*"